// utils/quotes.js
export const quotes = [
  "Discipline is choosing between what you want now and what you want most.",
  "You do not rise to the level of your goals. You fall to the level of your systems.",
  "A calm mind is a sharp blade.",
  "Consistency turns ordinary days into extraordinary outcomes.",
  "The future is built in the hours no one applauds.",
  "Your habits decide your direction long before you notice the distance.",
  "If it costs you your peace, it is too expensive.",
  "Small promises kept to yourself become self-respect.",
  "The moment you want to quit is the moment you need to remember why you started.",
  "The pain of discipline is lighter than the pain of regret.",
  "Nothing changes if nothing changes.",
  "Work quietly. Let results make the noise.",
  "Focus is not saying yes to what matters. It is saying no to what doesn’t.",
  "Time doesn’t get lost. It gets traded.",
  "A better life requires better boundaries.",
  "The standard you tolerate becomes your baseline.",
  "Your calendar is your real curriculum.",
  "Momentum is a decision repeated daily.",
  "You don’t need motivation. You need a plan.",
  "Progress is the proof of seriousness.",
  "You can’t think your way into a new life. You have to act your way into it.",
  "The goal is not perfection. The goal is alignment.",
  "The hardest part is starting. The second hardest part is continuing.",
  "When you feel behind, return to the next small step.",
  "Today is either day one or one day closer.",
  "Rest is earned by clarity, not by guilt.",
  "The difference between who you are and who you want to be is what you do daily.",
  "You become what you repeat.",
  "Make it easy to start and hard to stop.",
  "If you want a different outcome, build a different routine.",
];
